xsl0301_RAS_name = ""

Unit_Description_0016="A highly versatile combat and engineering unit useful on late-stage battlefields. Highly armored with good firepower. Upgradeable with cheap combat enhancements and powerful support enhancements."
Unit_Description_0020="Equips the SACU with a radar jammer that creates false radar signatures (countered by omni sensors) and greatly expands the range of its standard sensor systems.\n\n+84 Omni Radius\n+24 Vision Radius\nJamming Blips = 10\nJamming Radius = 16"
Unit_Description_0023="Massively increases the SACU's fire rate and mobility.\n\n+100% Main Cannon Rate of Fire\n+36% Movement Speed, Acceleration, and Turn Rate"
Unit_Description_0024="Increases main cannon's damage to 450 and grants it a small Area-Of-Effect damage radius.\n\n+150 Main cannon damage\n+1 Main cannon damage radius"
uel0301_IntelJammer_desc="SACU (Sensor/Jamming Preset)"
uel0301_IntelJammer_help="Enhanced during construction with the Intel Support System"
uel0301_IntelJammer_name=""
enhancements_0071="Intel Support System"
enhancements_0072="Remove Intel Support System"

Unit_Description_0115="A highly versatile combat and engineering unit useful on late-stage battlefields. Lightly armoured and slow, but highly upgradeable."
Unit_Description_0116="Personal Cloaking further hiding the SACU from optical sensors and providing a large HP boost. Countered by omni sensors. Costs a large amount of energy to run.\n\n+9000 Health"
Unit_Description_0117="Equips the SACU with an EMP Charge launcher, utterly disabling enemy units. Costs energy to fire.\n\nEMP Charge Launcher = 1000 damage, 5 damage radius, 13 seconds reload, 30000 energy firing cost\nStun Duration = 3 seconds (T3), 1 second (SACU & T4)"
Unit_Description_0118="Increases main cannon damage and range. Increases the range of the Pulsed Microwave Laser or EMP Charge Launcher if present.\n\n+200 Main cannon damage\n+7 Main cannon range\n+7 Pulsed Microwave Laser range\n+7 EMP Charge Launcher range"
Unit_Description_0119="Adds a versatile Nanite weapon system that can fire anti-air Missiles and anti-navy Torpedoes.\n\nNanite Missile System (Anti Air) - DPS: 462, Range: 70\nNanite Torpedo (Anti Navy) - DPS: 209, Range: 55"
Unit_Description_0122="Massively increases the rate at which the SACU repairs its armour as well as providing an HP boost.\n\n+7000 Health\n+225 Regen"
Unit_Description_0123="Personal Stealth hiding the SACU from radar. Countered by omni sensors. Costs energy to run. Also provides an HP boost.\n\n+6500 Health"
enhancements_0091="EMP Charge Launcher"
enhancements_0092="Remove EMP Charge Launcher"
Unit_Description_SacuRebalance_0001="Replaces the main cannon of the SACU with a powerful Pulsed Microwave Laser weapon.\n\nPulsed Microwave Laser DPS = 1000"
enhancements_0152_SacuRebalance="Pulsed Microwave Laser Generator"
enhancements_0153_SacuRebalance="Remove Pulsed Microwave Laser Generator"
url0301_Combat_desc="SACU (Laser Combatant preset)"
url0301_Rambo_desc="SACU (Laser Rambo preset)"
url0301_Cloak_desc="SACU (Cloak Laser preset)"

Unit_Description_0017="Increases SACU build speed and creates an Engineering Drone which act as a flying T3 Engineer. Assists the SACU by default, but can be given its own orders.\n\n+38 Buildpower\n+35 Buildpower Drone"
Unit_Description_0121="Massively increases SACU build speed.\n\n+73 Buildpower"
Unit_Description_0168="Massively increases SACU build speed.\n\n+73 Buildpower"
Unit_Description_0437="Massively increases SACU build speed.\n\n+73 Buildpower"
